import { addIcons } from 'ionicons';
import {
  homeOutline,
  home,
  heartOutline,
  heart,
  peopleOutline,
  people,
  compassOutline,
  compass,
  personCircleOutline,
  personCircle,
  starOutline,
  star,
  diamondOutline,
  diamond,
  walletOutline,
  cashOutline,
  giftOutline,
  trophyOutline,
  locationOutline,
  location,
  navigateOutline,
  notificationsOutline,
  checkmarkCircle,
  checkmarkCircleOutline,
  arrowForwardOutline,
  arrowBackOutline,
  addOutline,
  add,
  callOutline,
  chatbubbleEllipsesOutline,
  wineOutline,
  restaurantOutline,
  musicalNotesOutline,
  sparklesOutline,
  ribbonOutline,
  logInOutline,
  logOutOutline,
  lockClosedOutline,
  mailOutline,
  shieldCheckmarkOutline,
  flashOutline,
  timeOutline,
  cardOutline,
  trendingUpOutline,
  eyeOutline,
  closeOutline,
  checkmarkOutline,
  businessOutline,
  qrCodeOutline,
  pulseOutline,
  chevronForwardOutline,
  createOutline,
  informationCircleOutline,
} from 'ionicons/icons';

export function registerAppIcons(): void {
  addIcons({
    'home-outline': homeOutline,
    home,
    'heart-outline': heartOutline,
    heart,
    'people-outline': peopleOutline,
    people,
    'compass-outline': compassOutline,
    compass,
    'person-circle-outline': personCircleOutline,
    'person-circle': personCircle,
    'star-outline': starOutline,
    star,
    'diamond-outline': diamondOutline,
    diamond,
    'wallet-outline': walletOutline,
    'cash-outline': cashOutline,
    'gift-outline': giftOutline,
    'trophy-outline': trophyOutline,
    'location-outline': locationOutline,
    location,
    'navigate-outline': navigateOutline,
    'notifications-outline': notificationsOutline,
    'checkmark-circle': checkmarkCircle,
    'checkmark-circle-outline': checkmarkCircleOutline,
    'arrow-forward-outline': arrowForwardOutline,
    'arrow-back-outline': arrowBackOutline,
    'add-outline': addOutline,
    add,
    'call-outline': callOutline,
    'chatbubble-ellipses-outline': chatbubbleEllipsesOutline,
    'wine-outline': wineOutline,
    'restaurant-outline': restaurantOutline,
    'musical-notes-outline': musicalNotesOutline,
    'sparkles-outline': sparklesOutline,
    'ribbon-outline': ribbonOutline,
    'log-in-outline': logInOutline,
    'log-out-outline': logOutOutline,
    'lock-closed-outline': lockClosedOutline,
    'mail-outline': mailOutline,
    'shield-checkmark-outline': shieldCheckmarkOutline,
    'flash-outline': flashOutline,
    'time-outline': timeOutline,
    'card-outline': cardOutline,
    'trending-up-outline': trendingUpOutline,
    'eye-outline': eyeOutline,
    'close-outline': closeOutline,
    'checkmark-outline': checkmarkOutline,
    'business-outline': businessOutline,
    'qr-code-outline': qrCodeOutline,
    'pulse-outline': pulseOutline,
    'chevron-forward-outline': chevronForwardOutline,
    'create-outline': createOutline,
    'information-circle-outline': informationCircleOutline,
  });
}
