import { Member, StaffMember, Tier, Venue, VenueRequest } from './models';

export const TIERS: Tier[] = [
  {
    id: 'silver',
    name: 'Silver',
    threshold: 0,
    color: '#c4c7d0',
    tagline: 'Welcome to the list',
    perks: ['Skip-the-line at partner venues', 'Member pricing on bottle service', 'Birthday welcome drink'],
  },
  {
    id: 'gold',
    name: 'Gold',
    threshold: 5000,
    color: '#d4af37',
    tagline: 'Recognized at the door',
    perks: ['Priority entry, no wait', 'Reserved seating on request', 'Your bartender knows your order', 'Complimentary coat check'],
  },
  {
    id: 'platinum',
    name: 'Platinum',
    threshold: 15000,
    color: '#cfd8e6',
    tagline: 'The manager greets you by name',
    perks: ['Guaranteed table on arrival', 'Personal host at every venue', 'Early access to events & guest lists', 'Comp welcome bottle'],
  },
  {
    id: 'black',
    name: 'Black',
    threshold: 40000,
    color: '#2a2a34',
    tagline: 'Doors open before you arrive',
    perks: ['Dedicated concierge line', 'Off-menu & after-hours access', 'Private entrance where available', 'Curated experiences on request'],
  },
  {
    id: 'noir',
    name: 'Noir',
    threshold: 100000,
    color: '#0f0f16',
    tagline: 'The room is ready for you',
    perks: ['24/7 personal concierge', 'Anything, anywhere access', 'Private events & venue buyouts', 'Invitation-only Noir circle'],
  },
];

export const VENUES: Venue[] = [
  {
    id: 'v1',
    name: 'Skyline 88',
    address: '88 SE 3rd Ave, Miami, FL 33131',
    type: 'Rooftop',
    neighborhood: 'Downtown',
    city: 'Miami',
    image: '🌆',
    vibe: 'Sunset rooftop, house DJs, skyline views',
    memberTierRequired: 'silver',
    isMember: true,
    distanceMiles: 0.3,
    lat: 25.7617,
    lng: -80.1918,
    geofenceRadius: 250,
  },
  {
    id: 'v2',
    name: 'Velvet Room',
    address: '1235 Washington Ave, Miami Beach, FL 33139',
    type: 'Nightclub',
    neighborhood: 'South Beach',
    city: 'Miami',
    image: '🍸',
    vibe: 'High-energy club, bottle service, live sets',
    memberTierRequired: 'gold',
    isMember: true,
    distanceMiles: 1.1,
    lat: 25.7907,
    lng: -80.1300,
    geofenceRadius: 250,
  },
  {
    id: 'v3',
    name: 'The Cellar',
    address: '167 NW 23rd St, Miami, FL 33127',
    type: 'Speakeasy',
    neighborhood: 'Wynwood',
    city: 'Miami',
    image: '🥃',
    vibe: 'Hidden speakeasy, craft cocktails, jazz',
    memberTierRequired: 'gold',
    isMember: true,
    distanceMiles: 2.4,
    lat: 25.8010,
    lng: -80.1990,
    geofenceRadius: 250,
  },
  {
    id: 'v4',
    name: 'Marée',
    address: '1425 Brickell Ave, Miami, FL 33131',
    type: 'Restaurant',
    neighborhood: 'Brickell',
    city: 'Miami',
    image: '🦞',
    vibe: 'Coastal fine dining, chef\'s table',
    memberTierRequired: 'silver',
    isMember: false,
    distanceMiles: 0.8,
    lat: 25.7650,
    lng: -80.1930,
    geofenceRadius: 250,
  },
  {
    id: 'v5',
    name: 'Noir Society',
    address: '140 NE 39th St, Miami, FL 33137',
    type: 'Members Club',
    neighborhood: 'Design District',
    city: 'Miami',
    image: '🖤',
    vibe: 'Invitation-only members club & lounge',
    memberTierRequired: 'platinum',
    isMember: false,
    distanceMiles: 3.2,
    lat: 25.8130,
    lng: -80.1920,
    geofenceRadius: 250,
  },
  {
    id: 'v6',
    name: 'Azure Lounge',
    address: '9700 Collins Ave, Bal Harbour, FL 33154',
    type: 'Lounge',
    neighborhood: 'Bal Harbour',
    city: 'Miami',
    image: '🌊',
    vibe: 'Waterfront lounge, champagne & small plates',
    memberTierRequired: 'silver',
    isMember: false,
    distanceMiles: 5.6,
    lat: 25.8880,
    lng: -80.1260,
    geofenceRadius: 250,
  },
  {
    id: 'v7',
    name: 'Prohibition 21',
    address: '1421 SW 8th St, Miami, FL 33135',
    type: 'Speakeasy',
    neighborhood: 'Little Havana',
    city: 'Miami',
    image: '🎩',
    vibe: 'Password-entry speakeasy, rare spirits',
    memberTierRequired: 'gold',
    isMember: false,
    distanceMiles: 4.0,
    lat: 25.7650,
    lng: -80.2200,
    geofenceRadius: 250,
  },
  {
    id: 'v8',
    name: 'Solstice',
    address: '1445 Collins Ave, Miami Beach, FL 33139',
    type: 'Nightclub',
    neighborhood: 'South Beach',
    city: 'Miami',
    image: '☀️',
    vibe: 'Day-to-night megaclub, world-tour DJs',
    memberTierRequired: 'platinum',
    isMember: false,
    distanceMiles: 1.9,
    lat: 25.7920,
    lng: -80.1350,
    geofenceRadius: 250,
  },
];

export const STAFF: StaffMember[] = [
  {
    id: 's1',
    name: 'Diego Rivera',
    role: 'Bartender',
    venueId: 'v2',
    venueName: 'Velvet Room',
    avatar: 'DR',
    note: 'Makes your Old Fashioned exactly right — no cherry.',
  },
  {
    id: 's2',
    name: 'Sofia Marín',
    role: 'Event Manager',
    venueId: 'v2',
    venueName: 'Velvet Room',
    avatar: 'SM',
    note: 'Your go-to for tables and guest list.',
  },
  {
    id: 's3',
    name: 'Marcus Bell',
    role: 'Server',
    venueId: 'v1',
    venueName: 'Skyline 88',
    avatar: 'MB',
    note: 'Always saves the corner banquette at sunset.',
  },
  {
    id: 's4',
    name: 'Yuki Tanaka',
    role: 'Sommelier',
    venueId: 'v3',
    venueName: 'The Cellar',
    avatar: 'YT',
    note: 'Knows your taste in agave and Burgundy.',
  },
  {
    id: 's5',
    name: 'Priya Anand',
    role: 'Host',
    venueId: 'v1',
    venueName: 'Skyline 88',
    avatar: 'PA',
    note: 'Greets you at the elevator.',
  },
];

export const CURRENT_MEMBER: Member = {
  id: 'm1',
  firstName: 'Alex',
  lastName: 'Morgan',
  email: 'brandechomedia@gmail.com',
  memberSince: 2022,
  photo: '🕶️',
  totalSpent: 18450,
  totalTips: 3120,
  visitsThisYear: 27,
  preferences: {
    favoriteDrink: 'Old Fashioned',
    secondDrink: 'Dom Pérignon',
    spirit: 'Añejo tequila (Clase Azul)',
    seating: 'Corner banquette, away from speakers',
    music: 'Deep house / afrobeats',
    allergies: 'Shellfish',
    celebration: 'Anniversary — Sept 14',
    notes: 'Prefers a quiet welcome, no spotlight. Still water, no ice.',
  },
  favoriteVenueIds: ['v1', 'v2', 'v3'],
  favoriteStaffIds: ['s1', 's2', 's3', 's4'],
};

/**
 * The full member base. `CURRENT_MEMBER` (m1) is the signed-in member; the rest
 * populate the venue-side rosters and "expected tonight" lists. A member's
 * `favoriteVenueIds` doubles as the set of venues they have access to.
 */
export const MEMBERS: Member[] = [
  CURRENT_MEMBER,
  {
    id: 'm2',
    firstName: 'Jordan',
    lastName: 'Blake',
    email: 'jordan.blake@example.com',
    memberSince: 2020,
    photo: '🎩',
    totalSpent: 49200,
    totalTips: 8600,
    visitsThisYear: 41,
    preferences: {
      favoriteDrink: 'Macallan 18, neat',
      secondDrink: 'Krug Grande Cuvée',
      spirit: 'Single malt scotch',
      seating: 'Private booth, center of the room',
      music: 'Live jazz / soul',
      allergies: 'None',
      celebration: 'Closing big deals',
      notes: 'Big spender, loves being seen. Keep the bottle coming.',
    },
    favoriteVenueIds: ['v1', 'v2', 'v8'],
    favoriteStaffIds: ['s2', 's3'],
    arriving: { venueId: 'v1', etaMinutes: 3 },
  },
  {
    id: 'm3',
    firstName: 'Riley',
    lastName: 'Chen',
    email: 'riley.chen@example.com',
    memberSince: 2023,
    photo: '🕶️',
    totalSpent: 6800,
    totalTips: 1400,
    visitsThisYear: 12,
    preferences: {
      favoriteDrink: 'Espresso Martini',
      secondDrink: 'Veuve Clicquot',
      spirit: 'Vodka',
      seating: 'High-top near the DJ',
      music: 'Techno / house',
      allergies: 'Peanuts',
      celebration: 'Birthday — March 2',
      notes: 'Comes with a group of 4-6. Loves the energy up front.',
    },
    favoriteVenueIds: ['v1', 'v3'],
    favoriteStaffIds: ['s4'],
  },
  {
    id: 'm4',
    firstName: 'Sam',
    lastName: 'Okafor',
    email: 'sam.okafor@example.com',
    memberSince: 2021,
    photo: '👑',
    totalSpent: 17600,
    totalTips: 2900,
    visitsThisYear: 23,
    preferences: {
      favoriteDrink: 'Negroni',
      secondDrink: 'Dom Pérignon Rosé',
      spirit: 'Gin',
      seating: 'Quiet corner, good for conversation',
      music: 'Afrobeats / amapiano',
      allergies: 'Gluten',
      celebration: 'Anniversary — Nov 20',
      notes: 'Prefers gluten-free menu. Discreet service.',
    },
    favoriteVenueIds: ['v2', 'v5'],
    favoriteStaffIds: ['s1'],
    arriving: { venueId: 'v2', etaMinutes: 7 },
  },
  {
    id: 'm5',
    firstName: 'Toni',
    lastName: 'Alvarez',
    email: 'toni.alvarez@example.com',
    memberSince: 2024,
    photo: '💃',
    totalSpent: 1900,
    totalTips: 320,
    visitsThisYear: 5,
    preferences: {
      favoriteDrink: 'Aperol Spritz',
      secondDrink: 'Prosecco',
      spirit: 'Tequila blanco',
      seating: 'Patio / outdoors',
      music: 'Latin / reggaeton',
      allergies: 'None',
      celebration: 'Just getting started',
      notes: 'New member, building up. Friendly welcome goes a long way.',
    },
    favoriteVenueIds: ['v1'],
    favoriteStaffIds: ['s5'],
  },
  {
    id: 'm6',
    firstName: 'Casey',
    lastName: 'Nguyen',
    email: 'casey.nguyen@example.com',
    memberSince: 2019,
    photo: '🖤',
    totalSpent: 108000,
    totalTips: 21000,
    visitsThisYear: 58,
    preferences: {
      favoriteDrink: 'Louis XIII, neat',
      secondDrink: 'Cristal',
      spirit: 'Cognac',
      seating: 'The best table in the house — always',
      music: 'Whatever sets the mood',
      allergies: 'Shellfish',
      celebration: 'Every night is a celebration',
      notes: 'Top-tier Noir. Venue buyouts. Notify GM personally on arrival.',
    },
    favoriteVenueIds: ['v2', 'v5', 'v8'],
    favoriteStaffIds: ['s2'],
    arriving: { venueId: 'v8', etaMinutes: 11 },
  },
];

/** Pre-seeded access requests from other members, awaiting venue approval. */
export const SEED_REQUESTS: VenueRequest[] = [
  { memberId: 'm3', venueId: 'v2', status: 'requested', requestedAt: Date.now() - 3600_000, note: 'Would love in for my birthday.' },
  { memberId: 'm5', venueId: 'v2', status: 'requested', requestedAt: Date.now() - 7200_000 },
  { memberId: 'm2', venueId: 'v5', status: 'requested', requestedAt: Date.now() - 1800_000, note: 'Interested in a membership.' },
  { memberId: 'm4', venueId: 'v1', status: 'requested', requestedAt: Date.now() - 900_000 },
];
